.github/workflows/test.yml
Fixes github actions config to accurately reflect that the default branch, against which PRs are made, is named `main`.
=> Correct master to main in github actions config.

.github/dependabot.yml
This  adds a simple dependabot config to open PRs to update cargo dependencies to the latest version automatically.
=> Add dependabot config to update dependencies automatically.

Cargo.toml, Makefile, README.md, benchmark/Cargo.toml, benchmark/src/main.rs, benchmark/src/stats.rs, examples/batch.rs, examples/batch_send.rs, examples/env_callback.rs, examples/environment.rs, protocol/src/codec/decoder.rs, protocol/src/commands/deliver.rs, src/client/dispatcher.rs, src/client/metrics.rs, src/client/mod.rs, src/client/options.rs, src/consumer.rs, src/environment.rs, src/error.rs, src/lib.rs, src/producer.rs, tests/integration/consumer_test.rs, tests/integration/producer_test.rs
This PR add automatic batching on send. By default the batch size is `100` and it will cache the messages before sending them to the broker. The configuration on the producer `batch_delay`, which is by default `100ms` which is the schedule delay for the batch messages.
This PR also add two APIs on the `producer` for sending directly to the broker messages in batch, avoiding the delay mechanism.
Also the initial work for a benchmark tool has been done.
=> Implement publish batching

src/consumer.rs
This code is likely to be used in asynchronous environments. The usage
of `rand::thread_rng()` means that the consumer can never be sync and
send, because it uses a RC to cache the ThreadRng. It's only a very
small overhead to create a new context every time, and this will enable
calling code to also be asynchronous.
=> fix: Create new thread_rng rather than using cache

.github/workflows/publish.yml
Add github action to publish to crates.io when a tag is pushed.
Resolves #121
~Currently draft because the crates token needs to be added to secrets before merging.~
=> Publish to crates.io on tag.

protocol/src/codec/encoder.rs, protocol/src/message/amqp/types/descriptor.rs, protocol/src/message/amqp/types/primitives/simple.rs, src/client/message.rs, src/client/mod.rs
Implemented recommendations:
* combine duplicate match arms
* map.unrwap_or -> map_or
* change cloned -> copy when used with iterators
* remove redundant closures for method calls
* pass by reference when not consuming to avoid unnecessary allocations.
=> Implement some clippy pedantic recommendations.

Cargo.toml, src/client/mod.rs, src/client/options.rs, src/environment.rs, src/error.rs, src/lib.rs
This first implementation of TLS support includes:
- Integrate the tokio-native-tls library
- Implements an Environment Helper Class "TlsConfiguration" to manage Tls options in Environment
- Implements Tls trusting all hostnames and certificates at the moment (just encryption offered)
- Adding a test on port 5551
=> tls_first_implementation

src/client/mod.rs, src/environment.rs, src/producer.rs
This PR implements the heartbeat handling. 
It finishes the work started here 
https://github.com/rabbitmq/rabbitmq-stream-rust-client/pull/141 it sill not handle reconnection when the server is not reachable for x period. 
Implements #95 and fixes #162
=> Implements Heartbeat

examples/environment.rs, tests/integration/environment_test.rs
-  `environment_create_streams_with_parameters` create stream with parameter
- `environment_fail_tls_connection` fail to connect in a non-TLS server
About TLS, we could consider to setup a server with TLS in the CI. but it is out of scope for this PR
=> Add more tests for the Environment

protocol/Cargo.toml, protocol/src/message/amqp/types/annotations.rs, tests/integration/environment_test.rs, tests/integration/producer_test.rs
Add the implementation for get function.
Add tests for complex messages
=> Fix annotation get

tests/integration/client_test.rs, tests/integration/producer_test.rs
This PR adds more tests for the producer when:
- try to use the same id
- try to close twice 
- try to use it after close 
- test the deduplication with send batch 
There is a commented test:
```
producer_deduplication_send_after_close_error
```
because it does not work like the producer I will check it and open another PR
=> add tests for producer

Cargo.toml, examples/tls/producer.rs, examples/tls_producer.rs, src/client/mod.rs, src/client/options.rs, src/environment.rs, src/error.rs, tests/integration/environment_test.rs
This PR replaces tokio-native-tls with tokio::rusttls.
This was due because with tokio-native-tls certificate authentication wasn't working properly.
Comparing to previous release it also supports now certificate authentication and it adds an example
=> tls support improvements, added trust to hostname and ca certificate

src/consumer.rs, src/environment.rs, src/error.rs, tests/integration/consumer_test.rs
This closes https://github.com/rabbitmq/rabbitmq-stream-rust-client/issues/195
Exposes store_offset and query_offset in Consumer struct
=> expose store_offset and query_offset in consumer

benchmark/src/main.rs, protocol/src/message/amqp/body.rs, src/client/options.rs
Hello.
I was trying to use Client directly in my code, as in examples/raw_client.rs, and couldn't find a way to create ClientOptions
- Added ClientOptionsBuilder
- Added test
=> Add ClientOptionsBuilder

examples/raw_client.rs
It's important to remember that you need to set a handler before subscribing. Otherwise, some messages may be lost.
In this example, we perform publishing after subscribing, so losing messages is not possible. Nonetheless, it's better to adhere to this order.
=> Raw client example: set handler before subscribtion

protocol/src/commands/subscribe.rs, src/consumer.rs, tests/integration/consumer_test.rs
=> fixing bug when consuming from OffsetSpecification:Offset

examples/filtering.rs, examples/raw_client.rs, protocol/src/codec/decoder.rs, protocol/src/codec/encoder.rs, protocol/src/codec/mod.rs, protocol/src/commands/exchange_command_versions.rs, protocol/src/commands/mod.rs, protocol/src/commands/publish.rs, protocol/src/protocol.rs, protocol/src/request/mod.rs, protocol/src/request/shims.rs, protocol/src/response/mod.rs, protocol/src/types.rs, src/client/message.rs, src/client/mod.rs, src/consumer.rs, src/environment.rs, src/error.rs, src/lib.rs, src/producer.rs, tests/integration/client_test.rs, tests/integration/consumer_test.rs, tests/integration/producer_test.rs
Filtering supported
1. add exchange_command_versions command and check command version;
2. add version 2 encoder and decoder;
3. Implemented publish command version2，supporting the filtering feature;
4. Implemented producer and consumer filtering feature(like java client or python client).
=> Filtering supported

Dockerfile, protocol/src/commands/create_super_stream.rs, protocol/src/commands/delete_super_stream.rs, protocol/src/commands/mod.rs, protocol/src/commands/superstream_partitions.rs, protocol/src/commands/superstream_route.rs, protocol/src/protocol.rs, protocol/src/request/mod.rs, protocol/src/request/shims.rs, protocol/src/response/mod.rs, src/client/mod.rs, src/environment.rs, src/stream_creator.rs, tests/integration/client_test.rs, tests/integration/common.rs, tests/integration/environment_test.rs
This closes #9 
This closes #8 
This PR is a first step for super_stream implementation.
It implements:
- CREATE/DELETE super_stream commands
- PARTITIONS AND ROUTE commands
Integrate the commands in the Client
=> Superstream: Create/Delete superstream and Partition and route commands

src/client/dispatcher.rs, src/producer.rs, tests/integration/client_test.rs, tests/integration/common.rs, tests/integration/consumer_test.rs, tests/integration/producer_test.rs
Fix #233 by incrementing of one unit the publisher sequence returned from the query
Fixed also some unused warning
=> fix(producer): publisher sequence

src/consumer.rs
I think in the Consumer part we create a client on line 97 which creates a connection:
```
let mut client = self.environment.create_client().await?;
```
But then we create another one on line 123 without closing the previous one:
```
client = Client::connect(ClientOptions ....
```
Also in the close handle we don't close the locator connection.
This PR should solve the issue
=> close client connection in client consumer

src/consumer.rs, src/producer.rs
This closes https://github.com/rabbitmq/rabbitmq-stream-rust-client/issues/236
=> cleanup unused connections when load balancing mode is active

README.md, examples/batch_send.rs, examples/batch_send_with_tracing.rs, examples/send_async.rs, examples/send_with_confirm.rs
On the README at the moment we don't explain all the method we can use to send messages but we just give an example for send_with_confirm which is the slowest way to send messages (and likely not the most popular one used).
I created 3 examples: send_async, batch_send and send_with_confirm and modified the README accordingly
=> adding producer examples

examples/environment.rs, examples/receive_super_stream.rs, examples/send_super_stream.rs, src/client/mod.rs, src/client/options.rs, src/consumer.rs, src/environment.rs, src/producer.rs, src/superstream_consumer.rs, src/superstream_producer.rs, tests/integration/client_test.rs, tests/integration/consumer_test.rs, tests/integration/producer_test.rs
=> Add client properties

src/consumer.rs, src/environment.rs, src/producer.rs
Moving client connection creation from Producers/Consumers to Environment could help a better management of the disconnection in the future as this methods need to be called eventually to reconnect
=> Moving producers/consumers client connection creation to Environment

Cargo.toml, examples/batch_send.rs, examples/environment.rs, examples/superstreams/send_super_stream_hash.rs, examples/superstreams/send_super_stream_routing_key.rs, src/lib.rs, src/superstream.rs, src/superstream_consumer.rs, src/superstream_producer.rs
I notice the struct `SuperStreamProducer` is not exposed as `SuperStreamConsumer`. Even if it compiles, I cannot create a function that accepts or returns that type. This PR:
- expose `SuperStreamProducer`
- define `examples` under `examples/superstreams` that rust ignores.
- fix some clippy issues in examples/superstreams folder
- `RoutingStrategy` implements send + sync so also `SuperStreamProducer` implements send + sync
=> Expose SuperStreamProducer struct

Cargo.toml, src/client/mod.rs, tests/integration/consumer_test.rs, tests/integration/environment_test.rs
Update deps:
- tokio-rustls: `0.24.1` -> `0.26.1`
- `rustls::client::builder::ConfigBuilder` accepts directly CertificateDer and PrivateKeyDer.
- replace `with_safe_defaults` (https://docs.rs/rustls/0.21.1/rustls/struct.ConfigBuilder.html#method.with_safe_defaults) with `ConfigBuilder` (https://docs.rs/rustls/0.23.15/rustls/client/struct.ClientConfig.html#method.builder).
- use `dangerous` builder for untrusted client
- rustls-pemfile: `1.0.4` -> `2.2.0`
- apply clippy suggestions in integration test
=> Update `tokio-rustls` & `rustls-pemfile`

Cargo.toml, Makefile, examples/environment_deserialization.rs, examples/simple-consumer.rs, examples/tls_producer.rs, src/byte_capacity.rs, src/client/mod.rs, src/client/options.rs, src/environment.rs, src/lib.rs, tests/integration/environment_test.rs
This PR allow the deserialization for `ClientOption` and build `Environment from ClientOption`. See #268 
Changes:
- move `TlsConfiguration` under `client::options`
- `TlsConfiguration` is now an enum
- move the connection logic into `client::options`
- `TlsConfigurationBuilder::.build` may fail (**breaking**) instead of failing on `connect` with an `unwrap`.
- add `serde` feature
- `ClientOptions`, `TlsConfiguration`, and `ByteCapacity` are deserializable
- add test on deserialization
- move defaults to functions so `Default` and `serde` use the same defaults
- add `Environment::from_client_option` under `serde` feature
- add example
=> Deserialize `ClientOption` with serde

.tarpaulin.toml, Cargo.toml, examples/send_async.rs, examples/tls_producer.rs, protocol/src/message/builder.rs, src/bin/perf-producer.rs, src/client/mod.rs, src/client/options.rs, src/environment.rs, src/error.rs, src/producer.rs, tests/client_test.rs, tests/common.rs, tests/consumer_test.rs, tests/environment_test.rs, tests/integration/main.rs, tests/producer_test.rs
This PR implements a new method to send a message:
- `batch_send` follows the same flow as `send`
- every message is queued on a dedicated Tokio task and sent asynchronously
- if the internal producer is closed, the task stops to send
- remove `batch_publishing_delay` params (**breaking**)
- put integration tests under `tests` to avoid parallel execution. Parallel execution causes problems running the tests locally due to the limitation of the OS file description number.
- fix typo on method (publising_id -> publishing_id) (**breaking**)
- add an hardcoded timeout (1sec) to `send_with_confirm`
I introduced also a bin to calculate the latency performance to proof the improvement on low send rate. The bin creates a producer and a consumer. Every minute, 50 messages with the current …
=> Dynamic send

Cargo.toml, src/lib.rs
I see that the documentation build of the recent versions of docs.rs has failed:
https://docs.rs/crate/rabbitmq-stream-client/0.8.0/builds/1735995
After the repair, this command can run:
```shell
cargo +nightly rustdoc --all-features --lib --open -- --cfg docsrs
```
=> Fix doc build failed

Cargo.toml, src/client/mod.rs, src/lib.rs
The documentation build for the crate on docs.rs has been failing with an error that `doc(cfg(...))` is an experimental feature. Instead of fixing this, this changeset removes the only use of the feature from the `GenericTcpStream` enumeration, which is internal and does not show in documentation anyway.
=> Remove use of `doc(cfg(...))` and the docsrs configuration

src/producer.rs, tests/client_test.rs, tests/consumer_test.rs, tests/producer_test.rs
The channel never closed because the sender reference is kept by `MessageAccumulator`. That means `schedule_batch_send` loop never ends, so the lib creates a leak. This PR fixes this issue by removing the `MessageAccumulator` structure.
We also test how `close` and `drop` work on `clone`:
- `close` closes the underlying client, so every "linked" producer will be closed.
- `drop` closes the underlying client only if it is the last one.
Thanks for the help: @wolf4ood @cc90202
Fix #287
=> Fix task leak
